#!/bin/bash
convert sunburn_1.png -resize 33% sunburn_1.png
convert flood_1.png -resize 33% flood_1.png
convert flood_2.png -resize 33% flood_2.png
convert flood_3.png -resize 33% flood_3.png
convert flood_4.png -resize 33% flood_4.png
convert flood_5.png -resize 33% flood_5.png
convert flood_6.png -resize 33% flood_6.png
convert flood_7.png -resize 33% flood_7.png
convert flood_8.png -resize 33% flood_8.png
convert flood_9.png -resize 33% flood_9.png
convert flood_10.png -resize 33% flood_10.png
convert flood_11.png -resize 33% flood_11.png
convert flood_12.png -resize 33% flood_12.png
convert flood_13.png -resize 33% flood_13.png
convert flood_14.png -resize 33% flood_14.png
convert flood_15.png -resize 33% flood_15.png
convert flood_16.png -resize 33% flood_16.png
convert flood_17.png -resize 33% flood_17.png
convert flood_18.png -resize 33% flood_18.png
convert flood_19.png -resize 33% flood_19.png
convert flood_20.png -resize 33% flood_20.png
convert flood_21.png -resize 33% flood_21.png
convert flood_22.png -resize 33% flood_22.png
convert flood_23.png -resize 33% flood_23.png
convert flood_caused.png -resize 33% flood_caused.png
convert flood_flooded.png -resize 33% flood_flooded.png
convert sunburn_2.png -resize 33% sunburn_2.png
convert sunburn_3.png -resize 33% sunburn_3.png
convert sunburn_4.png -resize 33% sunburn_4.png
convert sunburn_5.png -resize 33% sunburn_5.png
convert sunburn_6.png -resize 33% sunburn_6.png
convert sunburn_7.png -resize 33% sunburn_7.png
convert sunburn_8.png -resize 33% sunburn_8.png
convert sunburn_9.png -resize 33% sunburn_9.png
convert sunburn_10.png -resize 33% sunburn_10.png
convert sunburn_11.png -resize 33% sunburn_11.png
convert sunburn_12.png -resize 33% sunburn_12.png
convert sunburn_13.png -resize 33% sunburn_13.png
convert sunburn_14.png -resize 33% sunburn_14.png
convert sunburn_burn.png -resize 33% sunburn_burn.png
convert sunburn_caused.png -resize 33% sunburn_caused.png